# Generated by Django 5.2.15 on 2026-07-16 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_emailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_kitchen_open',
            field=models.BooleanField(default=True),
        ),
    ]
