# Generated by Django 5.2.15 on 2026-07-16 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_avatar_user_last_stock_reset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vendor_auto_accept',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='vendor_timings',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='vendor_working_days',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
