# Generated by Django 5.2.15 on 2026-07-16 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_alter_order_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='available_qty',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(blank=True, default='Main', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='food_type',
            field=models.CharField(blank=True, choices=[('Veg', 'Veg'), ('Non-Veg', 'Non-Veg')], default='Veg', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='meal_type',
            field=models.CharField(blank=True, choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner')], default='Lunch', max_length=20, null=True),
        ),
    ]
